### PR TITLE
redirection /docs to https://docs.tinkerbell.org/ #160

### PR DESCRIPTION
**Pull request by geriadam**
## Description

Add redirection from /docs to https://docs.tinkerbell.org/

## Why is this needed

Issue https://github.com/tinkerbell/tinkerbell.org/issues/160

## How Has This Been Tested?

Open url /docs then redirect to https://docs.tinkerbell.org/

### CODE REVIEW

**Review by felixwidjaja — CHANGES_REQUESTED** [review]
I see changes for the new rules of redirection from /docs to docs. In line 172 and so on. However on line 32 we have old redirections targeting /docs
Can you make sure about this situation to @ronggur ? Thx.

**Comment by ronggur** [comment]
@geriadam lets remove all old redirections from /docs

**Comment by ronggur** [comment]
@felixwidjaja I guess save to remove

**Comment by ronggur** [comment]
Or we can keep it to keep old redirections remain

**Review by felixwidjaja — APPROVED** [review]

**Pull request merged**
