### PR TITLE
Sitemap & URL Update

### PR DESCRIPTION
**Pull request by ronggur**
## Description

This PR based on this file assigned to me https://docs.google.com/spreadsheets/d/1ozKp4tBdMCvzA6ysEz2-URwYtccJowS1Zxiu83TSTbg/edit#gid=0 by @felixwidjaja 

This PR will change urls and content structure and also add sitemap

Sitemap urls:

- /sitemap.xml

- /sitemap-terms.xml

- /sitemap-community.xml

- /sitemap-examples.xml

- /sitemap-docs.xml

## How Has This Been Tested?

- I test it by visiting new urls

- I can't test the redirections until this commit is in netlify staging

## How are existing users impacted? What migration steps/scripts do we need?

User will be redirect to all new urls

## Checklist:

I have:

- [x] restructure content for seo purpose
- [x] add redirections
- [x] create sitemap

### CODE REVIEW

**Comment by thomcrowe** [comment]
@ronggur there are some merge conflicts here - can you fix those and I'll look it over/approve it?

**Comment by ronggur** [comment]
@thomcrowe would you please check again, I already rebase the brach

**Comment by DailyAlice** [comment]
@ronggur Something seems to have happened to the ordering in the docs in this PR. About half of them are nested under the Documentation but they should be top-level.

**Comment by ronggur** [comment]
@DailyAlice let me know what needs to change. I am referencing this document for this PR https://docs.google.com/spreadsheets/d/1ozKp4tBdMCvzA6ysEz2-URwYtccJowS1Zxiu83TSTbg/edit#gid=0

**Comment by DailyAlice** [comment]
@ronggur , I'm not sure what should change, the urls look fine to me, but if you look at the deploy preview, some of the pages with URL changes end up nested under Documentation on the docs page, and some don't.
Screen Shot 2020-08-12 at 8 32 23 AM


Ideally, they wouldn't be nested and the table of contents would look like it currently does.
Screen Shot 2020-08-12 at 8 33 18 AM

Or if nesting is the new thing, the Templates and Workflows should also be in their places in the toc under Hardware Data and above Setup.

Also, the Concepts page was removed in a previous PR, so should also be removed from this one.

**Comment by ronggur** [comment]
@DailyAlice could you please check again https://deploy-preview-118--festive-goldwasser-489842.netlify.app/

**Comment by DailyAlice** [comment]
Hey @ronggur, this looks good, except that the first entry in the toc is no longer there. It seems there is no way to get back to the documentation landing page after navigating away from it. Can we add that back?

**Comment by ronggur** [comment]
@DailyAlice Please check again https://deploy-preview-118--festive-goldwasser-489842.netlify.app/docs/

**Comment by felixwidjaja** [comment]
Yep. all looks good, should be good to merge

**Pull request merged**
