### PR TITLE
#37 update some metadata

### PR DESCRIPTION
**Pull request by ronggur**

### CODE REVIEW

**Comment by ronggur** [comment]
@gauravgahlot this PR is ready to merge

**Comment by gauravgahlot** [comment]
@mrmrcoleman I don't have the context here. Can we have someone to review this PR?

**Comment by gauravgahlot** [comment]
@ronggur Could you please update the branch?

**Comment by thomcrowe** [comment]
@ronggur is this a PR that we still need to approve and merge?

**Comment by ronggur** [comment]
sorry @gauravgahlot @thomcrowe , already rebase the branch, so this is additional metadata for social sharing purpose

Screen Shot 2020-07-10 at 11 00 44

**Comment by mmlb** [comment]
@ronggur I think just needs a rebase on top of latest master.

**Pull request merged**
