### PR TITLE
bug: fix gotpl with or function

### PR DESCRIPTION
**Pull request by andy-v-h**
## Description

Corrects `gotpl` syntax to use `or` as a function.

## Why is this needed

In the 0.71.1 release of `hugo` there was a change that broke older compatibilities with `gotpl`. 

Fixes: #133 

## How Has This Been Tested?

I ran the site in a container locally

```bash
docker run --rm -it -v $(pwd):/src \
     -p 1313:1313 klakegg/hugo:0.82.0-alpine server
```

Then I manually tested functionality of the site; link, copy text boxes, top nav, side bars, etc.

## How are existing users impacted? What migration steps/scripts do we need?

Fixes a bug that prevented upgrading the site release to `hugo` `v0.82.0` or _latest_. 

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by mmlb** [comment]
lgtm, tested with nix-shell's hugo and the updated docker image

**Review by mmlb — APPROVED** [review]

**Review by mmlb — APPROVED** [review]

**Comment by mmlb** [comment]
/shrug, guess I don't have approval perms here.

**Review by Raj-Dharwadkar — COMMENTED** [review]
@tinkerbell/devrel

**Comment by jacobweinstock** [comment]
when someone from @tinkerbell/devrel has a moment, would they mind looking at this, please and thank you :)

**Review by displague — APPROVED** [review]

**Pull request merged**
