### PR TITLE
contributors page

### PR DESCRIPTION
**Pull request by ronggur**
add contributors page

### CODE REVIEW

**Comment by ronggur** [comment]
https://deploy-preview-85--festive-goldwasser-489842.netlify.app/contributors/

Screen Shot 2020-06-23 at 22 03 03

**Comment by mmlb** [comment]
@ronggur can we get a script that will fetch and update the yaml of the contributors?

**Comment by ronggur** [comment]
@mmlb the contributors.yaml is created manually https://github.com/ronggur/tinkerbell.org/blob/79-collaborator-page/data/contributors.yaml

**Comment by gauravgahlot** [comment]
@ronggur The page looks great to me. However, I agree with @mmlb that with automation in place new contributors will be automatically added to this page.

**Comment by ronggur** [comment]
@gauravgahlot I'm not sure how to do that because all I got from this issue #85 is https://docs.google.com/spreadsheets/d/1pLlyh5A3ZIhp8ePAxWY8CTvhUSm5rBXlGQ7pneoG50I/edit#gid=0

**Comment by ronggur** [comment]
anyway can we discuss it in this issue? #79

**Comment by mrmrcoleman** [comment]
@ronggur We have now approved a process for getting updates in https://github.com/tinkerbell/tinkerbell.org/issues/79

This can be merged.

**Pull request merged**
