### PR TITLE
Footer logo

### PR DESCRIPTION
**Pull request by geriadam**
updated logo home

### CODE REVIEW

**Review by felixwidjaja — APPROVED** [review]

**Review by felixwidjaja — APPROVED** [review]

**Comment by geriadam** [comment]
image
image

**Review by felixwidjaja — APPROVED** [review]

**Comment by felixwidjaja** [comment]
Hi @geriadam getting closer!
It's too close to FAQ. Maybe put the logo in below (line break)?

**Comment by felixwidjaja** [comment]
@geriadam can you please set <a> url to https://metal.equinix.com/ on both footers? Thanks.

**Comment by geriadam** [comment]
done sir @felixwidjaja

**Pull request merged**
