### PR TITLE
#23 add faq page

### PR DESCRIPTION
**Pull request by ronggur**
FAQ Page

### CODE REVIEW

**Comment by ronggur** [comment]
Screen Shot 2020-06-15 at 22 01 38

**Comment by ronggur** [comment]
@mrmrcoleman @gauravgahlot whey you have time, can you help review this PR? thanks

**Comment by mrmrcoleman** [comment]
@ronggur Will do

**Comment by ronggur** [comment]
@mrmrcoleman Thanks Sir

**Comment by mrmrcoleman** [comment]
@ronggur Added some changes.

**Comment by ronggur** [comment]
@mrmrcoleman ok Sir, I squash the commit

**Comment by mrmrcoleman** [comment]
I fixed the link for PBnJ. Should be done now.

**Comment by ronggur** [comment]
@mrmrcoleman commit squashed Sir

**Comment by mrmrcoleman** [comment]
Hey @ronggur I approved the changes. Please double check the content and then feel free to merge.

**Pull request merged**
