### PR TITLE
Update Action Images in Documentation

### PR DESCRIPTION
**Pull request by mohamed-rafraf**
## Description
I found mistakes in the Tinkerbell documentation where certain action image links were incorrect. 

## Why is this needed

Fixes: #

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by jacobweinstock** [comment]
Thanks for catching this, @mohamed-rafraf . You'll need to fix the DCO signoff. https://github.com/tinkerbell/tinkerbell.org/runs/25350305224

**Comment by jacobweinstock** [comment]
Hey @mohamed-rafraf , apologies for not getting to this sooner. While this update does update to images that actually exist in the registry, we have moved away from that old registry location. The old registry location `quay.io/tinkerbell-actions/` is replaced by the new location `quay.io/tinkerbell/actions`. But as you have already noticed, the `v` tags do not exist on the images at `quay.io/tinkerbell/actions`. We now use sha hashes and a latest tag only. 

Would you mind updating just the tags to either drop the tag or use `latest`?

**Comment by mohamed-rafraf** [comment]
Thank you for Information! I updated the images again

**Review by jacobweinstock — APPROVED** [review]
Thank you!

**Pull request merged**
