### PR TITLE
community-slack page

### PR DESCRIPTION
**Pull request by ronggur**
#39 Slack: More Guided

### CODE REVIEW

**Comment by ronggur** [comment]
@gauravgahlot this PR is ready to merge

**Comment by gauravgahlot** [comment]
@ronggur Do we an issue logged that can be linked to this PR?
We want to avoid updating anything in tinkerbell.org without a logged issue.  

cc: @mrmrcoleman

**Comment by ronggur** [comment]
@gauravgahlot, @felixwidjaja already open these issues #39 and #37

**Comment by gauravgahlot** [comment]
@felixwidjaja Is this good to merge?

**Pull request merged**
